### ISSUE TITLE
ByteScheduler: Profiler Bug with PyTorch

### ISSUE THREAD

**Issue by bjwdttz** [bytedance/byteps#119]
**Describe the bug**
When I was running a test using LeNet and MNIST with ByteScheduler's profiler, it raised an error in python and got stuck.

**To Reproduce**
1. mpirun --allow-run-as-root -wdir /home/user --mca orte_base_help_aggregate 0 -x NCCL_IB_DISABLE=1 -x NCCL_SOCKET_IFNAME=enp1s0f1 -x HOROVOD_GLOO=0 -x USE_BYTESCHEDULER=1 -x BYTESCHEDULER_DEBUG=1 -x BYTESCHEDULER_TIMELINE=/home/user/bsc_pushnpull_comm.trace.json -np 4 -H IP1:2,IP2:2 --display-map --display-allocation -map-by slot -bind-to none -nooversubscribe  -mca plm_rsh_args "-p 12945" --mca pml ob1 --mca btl ^openib --mca btl_tcp_if_exclude docker0,ens1f0,ens1f1,ens4f0,ens4f1,enp1s0f0,lo,virbr0,ib0,ib1 --tag-output python /home/user/byteps/bytescheduler/examples/pytorch_horovod_mnist.py
2. See error

**Screenshots**
- Complete Logs:
```
======================   ALLOCATED NODES   ======================
	IP1: flags=0x11 slots=2 max_slots=0 slots_inuse=0 state=UP
	IP2: flags=0x13 slots=2 max_slots=0 slots_inuse=0 state=UP
=================================================================
 Data for JOB [58557,1] offset 0 Total slots allocated 4

 ========================   JOB MAP   ========================

 Data for node: IP1	Num slots: 2	Max slots: 0	Num procs: 2
 	Process OMPI jobid: [58557,1] App: 0 Process rank: 0 Bound: N/A
 	Process OMPI jobid: [58557,1] App: 0 Process rank: 1 Bound: N/A

 Data for node: IP2	Num slots: 2	Max slots: 0	Num procs: 2
 	Process OMPI jobid: [58557,1] App: 0 Process rank: 2 Bound: N/A
 	Process OMPI jobid: [58557,1] App: 0 Process rank: 3 Bound: N/A

 =============================================================
 Data for JOB [58557,1] offset 0 Total slots allocated 4

 ========================   JOB MAP   ========================

 Data for node: IP1	Num slots: 2	Max slots: 0	Num procs: 2
 	Process OMPI jobid: [58557,1] App: 0 Process rank: 0 Bound: N/A
 	Process OMPI jobid: [58557,1] App: 0 Process rank: 1 Bound: N/A

 Data for node: IP2	Num slots: 2	Max slots: 0	Num procs: 2
 	Process OMPI jobid: [58557,1] App: 0 Process rank: 2 Bound: N/A
 	Process OMPI jobid: [58557,1] App: 0 Process rank: 3 Bound: N/A

 =============================================================
[1,3]<stderr>:14:16:54.302 __init__.py:16 WARNING: Enable debugging may seriously affect performance!
[1,0]<stderr>:14:16:54.322 __init__.py:16 WARNING: Enable debugging may seriously affect performance!
[1,2]<stderr>:14:16:54.435 __init__.py:16 WARNING: Enable debugging may seriously affect performance!
[1,1]<stderr>:14:16:54.435 __init__.py:16 WARNING: Enable debugging may seriously affect performance!
[1,3]<stdout>:hijack function <unbound method _DistributedOptimizer._register_hooks>
[1,3]<stdout>:function <unbound method _DistributedOptimizer._register_hooks> is hijacked to do nothing.
[1,0]<stdout>:hijack function <unbound method _DistributedOptimizer._register_hooks>
[1,0]<stdout>:function <unbound method _DistributedOptimizer._register_hooks> is hijacked to do nothing.
[1,3]<stderr>:/usr/local/lib/python2.7/dist-packages/torchvision/datasets/mnist.py:53: UserWarning: train_data has been renamed data
[1,3]<stderr>:  warnings.warn("train_data has been renamed data")
[1,0]<stderr>:/usr/local/lib/python2.7/dist-packages/torchvision/datasets/mnist.py:53: UserWarning: train_data has been renamed data
[1,0]<stderr>:  warnings.warn("train_data has been renamed data")
[1,2]<stdout>:hijack function <unbound method _DistributedOptimizer._register_hooks>
[1,2]<stdout>:function <unbound method _DistributedOptimizer._register_hooks> is hijacked to do nothing.
[1,1]<stdout>:hijack function <unbound method _DistributedOptimizer._register_hooks>
[1,1]<stdout>:function <unbound method _DistributedOptimizer._register_hooks> is hijacked to do nothing.
[1,2]<stderr>:/usr/local/lib/python2.7/dist-packages/torchvision/datasets/mnist.py:53: UserWarning: train_data has been renamed data
[1,2]<stderr>:  warnings.warn("train_data has been renamed data")
[1,1]<stderr>:/usr/local/lib/python2.7/dist-packages/torchvision/datasets/mnist.py:53: UserWarning: train_data has been renamed data
[1,1]<stderr>:  warnings.warn("train_data has been renamed data")
[1,3]<stderr>:14:16:55.023 horovod.py:42 DEBUG: hvd size 4, rank 3
[1,3]<stderr>:14:16:55.024 horovod.py:212 DEBUG: rank 3 registers forward hook on module Conv2d(1, 20, kernel_size=(5, 5), stride=(1, 1))
[1,3]<stderr>:14:16:55.024 horovod.py:212 DEBUG: rank 3 registers forward hook on module Conv2d(20, 50, kernel_size=(5, 5), stride=(1, 1))
[1,3]<stderr>:14:16:55.024 horovod.py:212 DEBUG: rank 3 registers forward hook on module Linear(in_features=800, out_features=500, bias=True)
[1,3]<stderr>:14:16:55.024 horovod.py:212 DEBUG: rank 3 registers forward hook on module Linear(in_features=500, out_features=10, bias=True)
[1,3]<stderr>:14:16:55.024 horovod.py:235 DEBUG: rank 3 calls make_hook for conv1.weight
[1,3]<stderr>:14:16:55.025 horovod.py:235 DEBUG: rank 3 calls make_hook for conv1.bias
[1,3]<stderr>:14:16:55.025 horovod.py:235 DEBUG: rank 3 calls make_hook for conv2.weight
[1,3]<stderr>:14:16:55.025 horovod.py:235 DEBUG: rank 3 calls make_hook for conv2.bias
[1,3]<stderr>:14:16:55.025 horovod.py:235 DEBUG: rank 3 calls make_hook for fc1.weight
[1,3]<stderr>:14:16:55.026 horovod.py:235 DEBUG: rank 3 calls make_hook for fc1.bias
[1,3]<stderr>:14:16:55.026 horovod.py:235 DEBUG: rank 3 calls make_hook for fc2.weight
[1,3]<stderr>:14:16:55.026 horovod.py:235 DEBUG: rank 3 calls make_hook for fc2.bias
[1,3]<stderr>:14:16:55.027 bytecore.py:124 INFO: start Core 3: credit 4000000.0, partition 1000000, credit tuning 1, partition tuning 0.
[1,0]<stderr>:14:16:55.052 horovod.py:42 DEBUG: hvd size 4, rank 0
[1,0]<stderr>:14:16:55.053 horovod.py:212 DEBUG: rank 0 registers forward hook on module Conv2d(1, 20, kernel_size=(5, 5), stride=(1, 1))
[1,0]<stderr>:14:16:55.053 horovod.py:212 DEBUG: rank 0 registers forward hook on module Conv2d(20, 50, kernel_size=(5, 5), stride=(1, 1))
[1,0]<stderr>:14:16:55.053 horovod.py:212 DEBUG: rank 0 registers forward hook on module Linear(in_features=800, out_features=500, bias=True)
[1,0]<stderr>:14:16:55.053 horovod.py:212 DEBUG: rank 0 registers forward hook on module Linear(in_features=500, out_features=10, bias=True)
[1,0]<stderr>:14:16:55.053 horovod.py:235 DEBUG: rank 0 calls make_hook for conv1.weight
[1,0]<stderr>:14:16:55.054 horovod.py:235 DEBUG: rank 0 calls make_hook for conv1.bias
[1,0]<stderr>:14:16:55.054 horovod.py:235 DEBUG: rank 0 calls make_hook for conv2.weight
[1,0]<stderr>:14:16:55.054 horovod.py:235 DEBUG: rank 0 calls make_hook for conv2.bias
[1,0]<stderr>:14:16:55.055 horovod.py:235 DEBUG: rank 0 calls make_hook for fc1.weight
[1,0]<stderr>:14:16:55.055 horovod.py:235 DEBUG: rank 0 calls make_hook for fc1.bias
[1,0]<stderr>:14:16:55.055 horovod.py:235 DEBUG: rank 0 calls make_hook for fc2.weight
[1,0]<stderr>:14:16:55.055 horovod.py:235 DEBUG: rank 0 calls make_hook for fc2.bias
[1,0]<stderr>:14:16:55.055 bytecore.py:102 INFO: rank 0: profiler is enabled.
[1,0]<stderr>:14:16:55.056 comm.py:185 INFO: Comm host: localhost, port: 58888
[1,0]<stderr>:14:16:55.057 search.py:119 INFO: Bayesian Search is enabled, space {'credit': (4.0, 64.0)}, max_num_steps 15.
[1,0]<stderr>:14:16:55.057 bytecore.py:124 INFO: start Core 0: credit 4000000.0, partition 1000000, credit tuning 1, partition tuning 0.
[1,2]<stderr>:14:16:55.123 horovod.py:42 DEBUG: hvd size 4, rank 2
[1,2]<stderr>:14:16:55.124 horovod.py:212 DEBUG: rank 2 registers forward hook on module Conv2d(1, 20, kernel_size=(5, 5), stride=(1, 1))
[1,2]<stderr>:14:16:55.124 horovod.py:212 DEBUG: rank 2 registers forward hook on module Conv2d(20, 50, kernel_size=(5, 5), stride=(1, 1))
[1,2]<stderr>:14:16:55.124 horovod.py:212 DEBUG: rank 2 registers forward hook on module Linear(in_features=800, out_features=500, bias=True)
[1,2]<stderr>:14:16:55.124 horovod.py:212 DEBUG: rank 2 registers forward hook on module Linear(in_features=500, out_features=10, bias=True)
[1,2]<stderr>:14:16:55.125 horovod.py:235 DEBUG: rank 2 calls make_hook for conv1.weight
[1,2]<stderr>:14:16:55.125 horovod.py:235 DEBUG: rank 2 calls make_hook for conv1.bias
[1,2]<stderr>:14:16:55.125 horovod.py:235 DEBUG: rank 2 calls make_hook for conv2.weight
[1,2]<stderr>:14:16:55.125 horovod.py:235 DEBUG: rank 2 calls make_hook for conv2.bias
[1,2]<stderr>:14:16:55.126 horovod.py:235 DEBUG: rank 2 calls make_hook for fc1.weight
[1,2]<stderr>:14:16:55.126 horovod.py:235 DEBUG: rank 2 calls make_hook for fc1.bias
[1,2]<stderr>:14:16:55.126 horovod.py:235 DEBUG: rank 2 calls make_hook for fc2.weight
[1,2]<stderr>:14:16:55.126 horovod.py:235 DEBUG: rank 2 calls make_hook for fc2.bias
[1,2]<stderr>:14:16:55.128 bytecore.py:124 INFO: start Core 2: credit 4000000.0, partition 1000000, credit tuning 1, partition tuning 0.
[1,1]<stderr>:14:16:55.147 horovod.py:42 DEBUG: hvd size 4, rank 1
[1,1]<stderr>:14:16:55.147 horovod.py:212 DEBUG: rank 1 registers forward hook on module Conv2d(1, 20, kernel_size=(5, 5), stride=(1, 1))
[1,1]<stderr>:14:16:55.148 horovod.py:212 DEBUG: rank 1 registers forward hook on module Conv2d(20, 50, kernel_size=(5, 5), stride=(1, 1))
[1,1]<stderr>:14:16:55.148 horovod.py:212 DEBUG: rank 1 registers forward hook on module Linear(in_features=800, out_features=500, bias=True)
[1,1]<stderr>:14:16:55.148 horovod.py:212 DEBUG: rank 1 registers forward hook on module Linear(in_features=500, out_features=10, bias=True)
[1,1]<stderr>:14:16:55.148 horovod.py:235 DEBUG: rank 1 calls make_hook for conv1.weight
[1,1]<stderr>:14:16:55.149 horovod.py:235 DEBUG: rank 1 calls make_hook for conv1.bias
[1,1]<stderr>:14:16:55.149 horovod.py:235 DEBUG: rank 1 calls make_hook for conv2.weight
[1,1]<stderr>:14:16:55.149 horovod.py:235 DEBUG: rank 1 calls make_hook for conv2.bias
[1,1]<stderr>:14:16:55.150 horovod.py:235 DEBUG: rank 1 calls make_hook for fc1.weight
[1,1]<stderr>:14:16:55.150 horovod.py:235 DEBUG: rank 1 calls make_hook for fc1.bias
[1,1]<stderr>:14:16:55.150 horovod.py:235 DEBUG: rank 1 calls make_hook for fc2.weight
[1,1]<stderr>:14:16:55.150 horovod.py:235 DEBUG: rank 1 calls make_hook for fc2.bias
[1,1]<stderr>:14:16:55.151 bytecore.py:124 INFO: start Core 1: credit 4000000.0, partition 1000000, credit tuning 1, partition tuning 0.
[1,0]<stderr>:14:16:55.271 horovod.py:92 DEBUG: rank 0 calls step() 0
[1,2]<stderr>:14:16:55.272 horovod.py:92 DEBUG: rank 2 calls step() 0
[1,1]<stderr>:14:16:55.272 horovod.py:92 DEBUG: rank 1 calls step() 0
[1,0]<stdout>:Model: lenet
[1,0]<stdout>:Batch size: 32
[1,0]<stdout>:Number of GPUs: 4
[1,0]<stdout>:Running warmup...
[1,3]<stderr>:14:16:55.273 horovod.py:92 DEBUG: rank 3 calls step() 0
[1,1]<stderr>:14:16:55.289 horovod.py:116 DEBUG: rank 1 calls zero_grad() of step 1
[1,1]<stderr>:14:16:55.290 horovod.py:203 DEBUG: rank 1 conv1.weight is ready.
[1,1]<stderr>:14:16:55.290 horovod.py:203 DEBUG: rank 1 conv1.bias is ready.
[1,3]<stderr>:14:16:55.290 horovod.py:116 DEBUG: rank 3 calls zero_grad() of step 1
[1,1]<stderr>:14:16:55.290 horovod.py:205 DEBUG: rank 1 starts forward Conv2d(1, 20, kernel_size=(5, 5), stride=(1, 1)).
[1,3]<stderr>:14:16:55.290 horovod.py:203 DEBUG: rank 3 conv1.weight is ready.
[1,3]<stderr>:14:16:55.290 horovod.py:203 DEBUG: rank 3 conv1.bias is ready.
[1,3]<stderr>:14:16:55.290 horovod.py:205 DEBUG: rank 3 starts forward Conv2d(1, 20, kernel_size=(5, 5), stride=(1, 1)).
[1,3]<stderr>:14:16:55.294 horovod.py:208 DEBUG: rank 3 finished forward Conv2d(1, 20, kernel_size=(5, 5), stride=(1, 1)).
[1,3]<stderr>:14:16:55.294 horovod.py:203 DEBUG: rank 3 conv2.weight is ready.
[1,3]<stderr>:14:16:55.295 horovod.py:203 DEBUG: rank 3 conv2.bias is ready.
[1,3]<stderr>:14:16:55.295 horovod.py:205 DEBUG: rank 3 starts forward Conv2d(20, 50, kernel_size=(5, 5), stride=(1, 1)).
[1,1]<stderr>:14:16:55.295 horovod.py:208 DEBUG: rank 1 finished forward Conv2d(1, 20, kernel_size=(5, 5), stride=(1, 1)).
[1,1]<stderr>:14:16:55.297 horovod.py:203 DEBUG: rank 1 conv2.weight is ready.
[1,3]<stderr>:14:16:55.297 horovod.py:208 DEBUG: rank 3 finished forward Conv2d(20, 50, kernel_size=(5, 5), stride=(1, 1)).
[1,1]<stderr>:14:16:55.297 horovod.py:203 DEBUG: rank 1 conv2.bias is ready.
[1,3]<stderr>:14:16:55.297 horovod.py:203 DEBUG: rank 3 fc1.weight is ready.
[1,3]<stderr>:14:16:55.297 horovod.py:203 DEBUG: rank 3 fc1.bias is ready.
[1,1]<stderr>:14:16:55.297 horovod.py:205 DEBUG: rank 1 starts forward Conv2d(20, 50, kernel_size=(5, 5), stride=(1, 1)).
[1,3]<stderr>:14:16:55.297 horovod.py:205 DEBUG: rank 3 starts forward Linear(in_features=800, out_features=500, bias=True).
[1,3]<stderr>:14:16:55.298 horovod.py:208 DEBUG: rank 3 finished forward Linear(in_features=800, out_features=500, bias=True).
[1,3]<stderr>:14:16:55.298 horovod.py:203 DEBUG: rank 3 fc2.weight is ready.
[1,3]<stderr>:14:16:55.298 horovod.py:203 DEBUG: rank 3 fc2.bias is ready.
[1,3]<stderr>:14:16:55.298 horovod.py:205 DEBUG: rank 3 starts forward Linear(in_features=500, out_features=10, bias=True).
[1,3]<stderr>:14:16:55.298 horovod.py:208 DEBUG: rank 3 finished forward Linear(in_features=500, out_features=10, bias=True).
[1,1]<stderr>:14:16:55.300 horovod.py:208 DEBUG: rank 1 finished forward Conv2d(20, 50, kernel_size=(5, 5), stride=(1, 1)).
[1,1]<stderr>:14:16:55.301 horovod.py:203 DEBUG: rank 1 fc1.weight is ready.
[1,1]<stderr>:14:16:55.301 horovod.py:203 DEBUG: rank 1 fc1.bias is ready.
[1,1]<stderr>:14:16:55.302 horovod.py:205 DEBUG: rank 1 starts forward Linear(in_features=800, out_features=500, bias=True).
[1,3]<stderr>:14:16:55.302 horovod.py:239 DEBUG: rank 3 finished backward of fc2.bias, delay 1
[1,3]<stderr>:14:16:55.302 bytetask.py:374 DEBUG: rank 3 step 1 task allreduce fc2.bias _additional_init is not implemented
[1,3]<stderr>:14:16:55.302 bytetask.py:89 DEBUG: rank 3 step 1 task allreduce fc2.bias was created
[1,3]<stderr>:14:16:55.303 horovod.py:239 DEBUG: rank 3 finished backward of fc2.weight, delay 1
[1,3]<stderr>:14:16:55.303 bytetask.py:374 DEBUG: rank 3 step 1 task allreduce fc2.weight _additional_init is not implemented
[1,1]<stderr>:14:16:55.303 horovod.py:208 DEBUG: rank 1 finished forward Linear(in_features=800, out_features=500, bias=True).
[1,3]<stderr>:14:16:55.304 bytetask.py:89 DEBUG: rank 3 step 1 task allreduce fc2.weight was created
[1,1]<stderr>:14:16:55.304 horovod.py:203 DEBUG: rank 1 fc2.weight is ready.
[1,1]<stderr>:14:16:55.304 horovod.py:203 DEBUG: rank 1 fc2.bias is ready.
[1,1]<stderr>:14:16:55.304 horovod.py:205 DEBUG: rank 1 starts forward Linear(in_features=500, out_features=10, bias=True).
[1,3]<stderr>:14:16:55.305 horovod.py:239 DEBUG: rank 3 finished backward of fc1.bias, delay 1
[1,1]<stderr>:14:16:55.305 horovod.py:208 DEBUG: rank 1 finished forward Linear(in_features=500, out_features=10, bias=True).
[1,3]<stderr>:14:16:55.305 bytetask.py:374 DEBUG: rank 3 step 1 task allreduce fc1.bias _additional_init is not implemented
[1,3]<stderr>:14:16:55.305 bytetask.py:89 DEBUG: rank 3 step 1 task allreduce fc1.bias was created
[1,3]<stderr>:14:16:55.306 horovod.py:239 DEBUG: rank 3 finished backward of fc1.weight, delay 1
[1,3]<stderr>:14:16:55.306 bytetask.py:374 DEBUG: rank 3 step 1 task allreduce fc1.weight _additional_init is not implemented
[1,2]<stderr>:14:16:55.306 horovod.py:116 DEBUG: rank 2 calls zero_grad() of step 1
[1,3]<stderr>:14:16:55.306 bytetask.py:89 DEBUG: rank 3 step 1 task allreduce fc1.weight was created
[1,2]<stderr>:14:16:55.306 horovod.py:203 DEBUG: rank 2 conv1.weight is ready.
[1,2]<stderr>:14:16:55.307 horovod.py:203 DEBUG: rank 2 conv1.bias is ready.
[1,2]<stderr>:14:16:55.307 horovod.py:205 DEBUG: rank 2 starts forward Conv2d(1, 20, kernel_size=(5, 5), stride=(1, 1)).
[1,1]<stderr>:14:16:55.308 horovod.py:239 DEBUG: rank 1 finished backward of fc2.bias, delay 1
[1,1]<stderr>:14:16:55.309 bytetask.py:374 DEBUG: rank 1 step 1 task allreduce fc2.bias _additional_init is not implemented
[1,1]<stderr>:14:16:55.309 bytetask.py:89 DEBUG: rank 1 step 1 task allreduce fc2.bias was created
[1,1]<stderr>:14:16:55.310 horovod.py:239 DEBUG: rank 1 finished backward of fc2.weight, delay 1
[1,1]<stderr>:14:16:55.310 bytetask.py:374 DEBUG: rank 1 step 1 task allreduce fc2.weight _additional_init is not implemented
[1,1]<stderr>:14:16:55.311 bytetask.py:89 DEBUG: rank 1 step 1 task allreduce fc2.weight was created
[1,2]<stderr>:14:16:55.311 horovod.py:208 DEBUG: rank 2 finished forward Conv2d(1, 20, kernel_size=(5, 5), stride=(1, 1)).
[1,0]<stderr>:14:16:55.311 horovod.py:116 DEBUG: rank 0 calls zero_grad() of step 1
[1,0]<stderr>:14:16:55.311 horovod.py:203 DEBUG: rank 0 conv1.weight is ready.
[1,0]<stderr>:14:16:55.311 horovod.py:203 DEBUG: rank 0 conv1.bias is ready.
[1,0]<stderr>:14:16:55.311 horovod.py:205 DEBUG: rank 0 starts forward Conv2d(1, 20, kernel_size=(5, 5), stride=(1, 1)).
[1,2]<stderr>:14:16:55.312 horovod.py:203 DEBUG: rank 2 conv2.weight is ready.
[1,2]<stderr>:14:16:55.312 horovod.py:203 DEBUG: rank 2 conv2.bias is ready.
[1,2]<stderr>:14:16:55.312 horovod.py:205 DEBUG: rank 2 starts forward Conv2d(20, 50, kernel_size=(5, 5), stride=(1, 1)).
[1,1]<stderr>:14:16:55.313 horovod.py:239 DEBUG: rank 1 finished backward of fc1.bias, delay 1
[1,3]<stderr>:14:16:55.313 horovod.py:239 DEBUG: rank 3 finished backward of conv2.weight, delay 1
[1,3]<stderr>:14:16:55.314 bytetask.py:374 DEBUG: rank 3 step 1 task allreduce conv2.weight _additional_init is not implemented
[1,3]<stderr>:14:16:55.314 bytetask.py:89 DEBUG: rank 3 step 1 task allreduce conv2.weight was created
[1,1]<stderr>:14:16:55.313 bytetask.py:374 DEBUG: rank 1 step 1 task allreduce fc1.bias _additional_init is not implemented
[1,3]<stderr>:14:16:55.314 horovod.py:239 DEBUG: rank 3 finished backward of conv2.bias, delay 1
[1,3]<stderr>:14:16:55.314 bytetask.py:374 DEBUG: rank 3 step 1 task allreduce conv2.bias _additional_init is not implemented
[1,1]<stderr>:14:16:55.314 bytetask.py:89 DEBUG: rank 1 step 1 task allreduce fc1.bias was created
[1,3]<stderr>:14:16:55.314 bytetask.py:89 DEBUG: rank 3 step 1 task allreduce conv2.bias was created
[1,1]<stderr>:14:16:55.314 horovod.py:239 DEBUG: rank 1 finished backward of fc1.weight, delay 1
[1,1]<stderr>:14:16:55.315 bytetask.py:374 DEBUG: rank 1 step 1 task allreduce fc1.weight _additional_init is not implemented
[1,0]<stderr>:14:16:55.315 horovod.py:208 DEBUG: rank 0 finished forward Conv2d(1, 20, kernel_size=(5, 5), stride=(1, 1)).
[1,1]<stderr>:14:16:55.315 bytetask.py:89 DEBUG: rank 1 step 1 task allreduce fc1.weight was created
[1,2]<stderr>:14:16:55.315 horovod.py:208 DEBUG: rank 2 finished forward Conv2d(20, 50, kernel_size=(5, 5), stride=(1, 1)).
[1,0]<stderr>:14:16:55.315 horovod.py:203 DEBUG: rank 0 conv2.weight is ready.
[1,2]<stderr>:14:16:55.316 horovod.py:203 DEBUG: rank 2 fc1.weight is ready.
[1,0]<stderr>:14:16:55.316 horovod.py:203 DEBUG: rank 0 conv2.bias is ready.
[1,0]<stderr>:14:16:55.316 horovod.py:205 DEBUG: rank 0 starts forward Conv2d(20, 50, kernel_size=(5, 5), stride=(1, 1)).
[1,2]<stderr>:14:16:55.316 horovod.py:203 DEBUG: rank 2 fc1.bias is ready.
[1,2]<stderr>:14:16:55.316 horovod.py:205 DEBUG: rank 2 starts forward Linear(in_features=800, out_features=500, bias=True).
[1,2]<stderr>:14:16:55.317 horovod.py:208 DEBUG: rank 2 finished forward Linear(in_features=800, out_features=500, bias=True).
[1,2]<stderr>:14:16:55.317 horovod.py:203 DEBUG: rank 2 fc2.weight is ready.
[1,2]<stderr>:14:16:55.317 horovod.py:203 DEBUG: rank 2 fc2.bias is ready.
[1,2]<stderr>:14:16:55.317 horovod.py:205 DEBUG: rank 2 starts forward Linear(in_features=500, out_features=10, bias=True).
[1,3]<stderr>:14:16:55.317 horovod.py:239 DEBUG: rank 3 finished backward of conv1.weight, delay 1
[1,2]<stderr>:14:16:55.318 horovod.py:208 DEBUG: rank 2 finished forward Linear(in_features=500, out_features=10, bias=True).
[1,3]<stderr>:14:16:55.318 bytetask.py:374 DEBUG: rank 3 step 1 task allreduce conv1.weight _additional_init is not implemented
[1,3]<stderr>:14:16:55.318 bytetask.py:89 DEBUG: rank 3 step 1 task allreduce conv1.weight was created
[1,0]<stderr>:14:16:55.318 horovod.py:208 DEBUG: rank 0 finished forward Conv2d(20, 50, kernel_size=(5, 5), stride=(1, 1)).
[1,3]<stderr>:14:16:55.318 horovod.py:239 DEBUG: rank 3 finished backward of conv1.bias, delay 1
[1,3]<stderr>:14:16:55.318 bytetask.py:374 DEBUG: rank 3 step 1 task allreduce conv1.bias _additional_init is not implemented
[1,0]<stderr>:14:16:55.318 horovod.py:203 DEBUG: rank 0 fc1.weight is ready.
[1,3]<stderr>:14:16:55.319 bytetask.py:89 DEBUG: rank 3 step 1 task allreduce conv1.bias was created
[1,0]<stderr>:14:16:55.318 horovod.py:203 DEBUG: rank 0 fc1.bias is ready.
[1,0]<stderr>:14:16:55.319 horovod.py:205 DEBUG: rank 0 starts forward Linear(in_features=800, out_features=500, bias=True).
[1,3]<stderr>:14:16:55.319 horovod.py:92 DEBUG: rank 3 calls step() 1
[1,0]<stderr>:14:16:55.320 horovod.py:208 DEBUG: rank 0 finished forward Linear(in_features=800, out_features=500, bias=True).
[1,0]<stderr>:14:16:55.320 horovod.py:203 DEBUG: rank 0 fc2.weight is ready.
[1,0]<stderr>:14:16:55.320 horovod.py:203 DEBUG: rank 0 fc2.bias is ready.
[1,0]<stderr>:14:16:55.320 horovod.py:205 DEBUG: rank 0 starts forward Linear(in_features=500, out_features=10, bias=True).
[1,1]<stderr>:14:16:55.320 horovod.py:239 DEBUG: rank 1 finished backward of conv2.weight, delay 1
[1,0]<stderr>:14:16:55.320 horovod.py:208 DEBUG: rank 0 finished forward Linear(in_features=500, out_features=10, bias=True).
[1,1]<stderr>:14:16:55.320 bytetask.py:374 DEBUG: rank 1 step 1 task allreduce conv2.weight _additional_init is not implemented
[1,1]<stderr>:14:16:55.321 bytetask.py:89 DEBUG: rank 1 step 1 task allreduce conv2.weight was created
[1,1]<stderr>:14:16:55.321 horovod.py:239 DEBUG: rank 1 finished backward of conv2.bias, delay 1
[1,2]<stderr>:14:16:55.322 horovod.py:239 DEBUG: rank 2 finished backward of fc2.bias, delay 1
[1,1]<stderr>:14:16:55.322 bytetask.py:374 DEBUG: rank 1 step 1 task allreduce conv2.bias _additional_init is not implemented
[1,1]<stderr>:14:16:55.322 bytetask.py:89 DEBUG: rank 1 step 1 task allreduce conv2.bias was created
[1,2]<stderr>:14:16:55.322 bytetask.py:374 DEBUG: rank 2 step 1 task allreduce fc2.bias _additional_init is not implemented
[1,2]<stderr>:14:16:55.323 bytetask.py:89 DEBUG: rank 2 step 1 task allreduce fc2.bias was created
[1,2]<stderr>:14:16:55.323 horovod.py:239 DEBUG: rank 2 finished backward of fc2.weight, delay 1
[1,2]<stderr>:14:16:55.324 bytetask.py:374 DEBUG: rank 2 step 1 task allreduce fc2.weight _additional_init is not implemented
[1,2]<stderr>:14:16:55.324 bytetask.py:89 DEBUG: rank 2 step 1 task allreduce fc2.weight was created
[1,2]<stderr>:14:16:55.325 horovod.py:239 DEBUG: rank 2 finished backward of fc1.bias, delay 1
[1,2]<stderr>:14:16:55.325 bytetask.py:374 DEBUG: rank 2 step 1 task allreduce fc1.bias _additional_init is not implemented
[1,0]<stderr>:14:16:55.325 horovod.py:239 DEBUG: rank 0 finished backward of fc2.bias, delay 1
[1,2]<stderr>:14:16:55.325 bytetask.py:89 DEBUG: rank 2 step 1 task allreduce fc1.bias was created
[1,0]<stderr>:14:16:55.325 bytetask.py:374 DEBUG: rank 0 step 1 task allreduce fc2.bias _additional_init is not implemented
[1,0]<stderr>:14:16:55.325 bytetask.py:89 DEBUG: rank 0 step 1 task allreduce fc2.bias was created
[1,0]<stderr>:14:16:55.325 bytetask.py:108 DEBUG: rank 0 step 1 task allreduce fc2.bias prepare() started
[1,2]<stderr>:14:16:55.326 horovod.py:239 DEBUG: rank 2 finished backward of fc1.weight, delay 1
[1,2]<stderr>:14:16:55.326 bytetask.py:374 DEBUG: rank 2 step 1 task allreduce fc1.weight _additional_init is not implemented
[1,2]<stderr>:14:16:55.326 bytetask.py:89 DEBUG: rank 2 step 1 task allreduce fc1.weight was created
[1,0]<stderr>:14:16:55.326 horovod.py:147 DEBUG: rank 0 fc2.bias tensor is ready for scheduling.
[1,0]<stderr>:14:16:55.326 horovod.py:239 DEBUG: rank 0 finished backward of fc2.weight, delay 1
[1,0]<stderr>:14:16:55.326 bytetask.py:205 DEBUG: rank 0 step 1 task allreduce fc2.bias is ready
[1,0]<stderr>:14:16:55.327 bytetask.py:374 DEBUG: rank 0 step 1 task allreduce fc2.weight _additional_init is not implemented
[1,0]<stderr>:14:16:55.327 bytecore.py:203 DEBUG: rank 0 step 1 task allreduce fc2.bias has been posted into Core with priority 7000
[1,1]<stderr>:14:16:55.328 horovod.py:239 DEBUG: rank 1 finished backward of conv1.weight, delay 1
[1,0]<stderr>:14:16:55.328 bytetask.py:89 DEBUG: rank 0 step 1 task allreduce fc2.weight was created
[1,1]<stderr>:14:16:55.328 bytetask.py:374 DEBUG: rank 1 step 1 task allreduce conv1.weight _additional_init is not implemented
[1,0]<stderr>:14:16:55.328 bytetask.py:108 DEBUG: rank 0 step 1 task allreduce fc2.weight prepare() started
[1,1]<stderr>:14:16:55.329 bytetask.py:89 DEBUG: rank 1 step 1 task allreduce conv1.weight was created
[1,0]<stderr>:14:16:55.329 horovod.py:147 DEBUG: rank 0 fc2.weight tensor is ready for scheduling.
[1,1]<stderr>:14:16:55.329 horovod.py:239 DEBUG: rank 1 finished backward of conv1.bias, delay 1
[1,0]<stderr>:Exception in thread Thread-1:
[1,0]<stderr>:Traceback (most recent call last):
[1,0]<stderr>:  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
[1,0]<stderr>:    self.run()
[1,0]<stderr>:  File "/usr/lib/python2.7/threading.py", line 754, in run
[1,0]<stderr>:    self.__target(*self.__args, **self.__kwargs)
[1,0]<stderr>:  File "/usr/local/lib/python2.7/dist-packages/bytescheduler-0.1.0-py2.7-linux-x86_64.egg/bytescheduler/common/bytecore.py", line 247, in _loop
[1,0]<stderr>:    self._profiler.put(task.name, task.op + 'QUEUE', 'E')
[1,0]<stderr>:  File "/usr/local/lib/python2.7/dist-packages/bytescheduler-0.1.0-py2.7-linux-x86_64.egg/bytescheduler/common/profiler.py", line 72, in put
[1,0]<stderr>:    self._events.put(self._cache[tensor+activity])
[1,0]<stderr>:KeyError: 'fc2.biasALLREDUCEQUEUE'
[1,0]<stderr>:14:16:55.329 bytetask.py:205 DEBUG: rank 0 step 1 task allreduce fc2.weight is ready
[1,0]<stderr>:
[1,1]<stderr>:14:16:55.330 bytetask.py:374 DEBUG: rank 1 step 1 task allreduce conv1.bias _additional_init is not implemented
[1,1]<stderr>:14:16:55.330 bytetask.py:89 DEBUG: rank 1 step 1 task allreduce conv1.bias was created
[1,0]<stderr>:14:16:55.330 bytecore.py:203 DEBUG: rank 0 step 1 task allreduce fc2.weight has been posted into Core with priority 6000
[1,0]<stderr>:14:16:55.330 horovod.py:239 DEBUG: rank 0 finished backward of fc1.bias, delay 1
[1,1]<stderr>:14:16:55.330 horovod.py:92 DEBUG: rank 1 calls step() 1
[1,0]<stderr>:14:16:55.331 bytetask.py:374 DEBUG: rank 0 step 1 task allreduce fc1.bias _additional_init is not implemented
[1,0]<stderr>:14:16:55.331 bytetask.py:89 DEBUG: rank 0 step 1 task allreduce fc1.bias was created
[1,3]<stderr>:14:16:55.331 horovod.py:116 DEBUG: rank 3 calls zero_grad() of step 2
[1,0]<stderr>:14:16:55.331 bytetask.py:108 DEBUG: rank 0 step 1 task allreduce fc1.bias prepare() started
[1,0]<stderr>:14:16:55.331 horovod.py:147 DEBUG: rank 0 fc1.bias tensor is ready for scheduling.
[1,0]<stderr>:14:16:55.332 bytetask.py:205 DEBUG: rank 0 step 1 task allreduce fc1.bias is ready
[1,2]<stderr>:14:16:55.332 horovod.py:239 DEBUG: rank 2 finished backward of conv2.weight, delay 1
[1,0]<stderr>:14:16:55.332 horovod.py:239 DEBUG: rank 0 finished backward of fc1.weight, delay 1
[1,2]<stderr>:14:16:55.332 bytetask.py:374 DEBUG: rank 2 step 1 task allreduce conv2.weight _additional_init is not implemented
[1,0]<stderr>:14:16:55.332 bytetask.py:374 DEBUG: rank 0 step 1 task allreduce fc1.weight _additional_init is not implemented
[1,2]<stderr>:14:16:55.332 bytetask.py:89 DEBUG: rank 2 step 1 task allreduce conv2.weight was created
[1,0]<stderr>:14:16:55.332 bytecore.py:203 DEBUG: rank 0 step 1 task allreduce fc1.bias has been posted into Core with priority 5000
[1,2]<stderr>:14:16:55.333 horovod.py:239 DEBUG: rank 2 finished backward of conv2.bias, delay 1
[1,0]<stderr>:14:16:55.333 bytetask.py:89 DEBUG: rank 0 step 1 task allreduce fc1.weight was created
[1,2]<stderr>:14:16:55.333 bytetask.py:374 DEBUG: rank 2 step 1 task allreduce conv2.bias _additional_init is not implemented
[1,0]<stderr>:14:16:55.333 bytetask.py:108 DEBUG: rank 0 step 1 task allreduce fc1.weight prepare() started
[1,2]<stderr>:14:16:55.334 bytetask.py:89 DEBUG: rank 2 step 1 task allreduce conv2.bias was created
[1,0]<stderr>:14:16:55.333 horovod.py:147 DEBUG: rank 0 fc1.weight tensor is ready for scheduling.
[1,0]<stderr>:14:16:55.334 bytetask.py:205 DEBUG: rank 0 step 1 task allreduce fc1.weight is ready
[1,0]<stderr>:14:16:55.334 bytecore.py:203 DEBUG: rank 0 step 1 task allreduce fc1.weight has been posted into Core with priority 4000
[1,2]<stderr>:14:16:55.337 horovod.py:239 DEBUG: rank 2 finished backward of conv1.weight, delay 1
[1,2]<stderr>:14:16:55.337 bytetask.py:374 DEBUG: rank 2 step 1 task allreduce conv1.weight _additional_init is not implemented
[1,2]<stderr>:14:16:55.337 bytetask.py:89 DEBUG: rank 2 step 1 task allreduce conv1.weight was created
[1,2]<stderr>:14:16:55.338 horovod.py:239 DEBUG: rank 2 finished backward of conv1.bias, delay 1
[1,2]<stderr>:14:16:55.338 bytetask.py:374 DEBUG: rank 2 step 1 task allreduce conv1.bias _additional_init is not implemented
[1,2]<stderr>:14:16:55.338 bytetask.py:89 DEBUG: rank 2 step 1 task allreduce conv1.bias was created
[1,2]<stderr>:14:16:55.339 horovod.py:92 DEBUG: rank 2 calls step() 1
[1,0]<stderr>:14:16:55.338 horovod.py:239 DEBUG: rank 0 finished backward of conv2.weight, delay 1
[1,0]<stderr>:14:16:55.339 bytetask.py:374 DEBUG: rank 0 step 1 task allreduce conv2.weight _additional_init is not implemented
[1,0]<stderr>:14:16:55.339 bytetask.py:89 DEBUG: rank 0 step 1 task allreduce conv2.weight was created
[1,0]<stderr>:14:16:55.339 bytetask.py:108 DEBUG: rank 0 step 1 task allreduce conv2.weight prepare() started
[1,0]<stderr>:14:16:55.339 horovod.py:147 DEBUG: rank 0 conv2.weight tensor is ready for scheduling.
[1,0]<stderr>:14:16:55.339 horovod.py:239 DEBUG: rank 0 finished backward of conv2.bias, delay 1
[1,0]<stderr>:14:16:55.340 bytetask.py:205 DEBUG: rank 0 step 1 task allreduce conv2.weight is ready
[1,0]<stderr>:14:16:55.340 bytetask.py:374 DEBUG: rank 0 step 1 task allreduce conv2.bias _additional_init is not implemented
[1,0]<stderr>:14:16:55.340 bytecore.py:203 DEBUG: rank 0 step 1 task allreduce conv2.weight has been posted into Core with priority 2000
[1,0]<stderr>:14:16:55.340 bytetask.py:89 DEBUG: rank 0 step 1 task allreduce conv2.bias was created
[1,0]<stderr>:14:16:55.341 bytetask.py:108 DEBUG: rank 0 step 1 task allreduce conv2.bias prepare() started
[1,0]<stderr>:14:16:55.341 horovod.py:147 DEBUG: rank 0 conv2.bias tensor is ready for scheduling.
[1,0]<stderr>:14:16:55.341 bytetask.py:205 DEBUG: rank 0 step 1 task allreduce conv2.bias is ready
[1,0]<stderr>:14:16:55.341 bytecore.py:203 DEBUG: rank 0 step 1 task allreduce conv2.bias has been posted into Core with priority 3000
[1,0]<stderr>:14:16:55.344 horovod.py:239 DEBUG: rank 0 finished backward of conv1.weight, delay 1
[1,0]<stderr>:14:16:55.344 bytetask.py:374 DEBUG: rank 0 step 1 task allreduce conv1.weight _additional_init is not implemented
[1,0]<stderr>:14:16:55.345 bytetask.py:89 DEBUG: rank 0 step 1 task allreduce conv1.weight was created
[1,1]<stderr>:14:16:55.345 horovod.py:116 DEBUG: rank 1 calls zero_grad() of step 2
[1,0]<stderr>:14:16:55.345 bytetask.py:108 DEBUG: rank 0 step 1 task allreduce conv1.weight prepare() started
[1,0]<stderr>:14:16:55.345 horovod.py:147 DEBUG: rank 0 conv1.weight tensor is ready for scheduling.
[1,0]<stderr>:14:16:55.345 horovod.py:239 DEBUG: rank 0 finished backward of conv1.bias, delay 1
[1,0]<stderr>:14:16:55.345 bytetask.py:205 DEBUG: rank 0 step 1 task allreduce conv1.weight is ready
[1,0]<stderr>:14:16:55.346 bytetask.py:374 DEBUG: rank 0 step 1 task allreduce conv1.bias _additional_init is not implemented
[1,0]<stderr>:14:16:55.346 bytetask.py:89 DEBUG: rank 0 step 1 task allreduce conv1.bias was created
[1,0]<stderr>:14:16:55.346 bytecore.py:203 DEBUG: rank 0 step 1 task allreduce conv1.weight has been posted into Core with priority 0
[1,0]<stderr>:14:16:55.347 bytetask.py:108 DEBUG: rank 0 step 1 task allreduce conv1.bias prepare() started
[1,0]<stderr>:14:16:55.347 horovod.py:147 DEBUG: rank 0 conv1.bias tensor is ready for scheduling.
[1,0]<stderr>:14:16:55.347 horovod.py:92 DEBUG: rank 0 calls step() 1
[1,0]<stderr>:14:16:55.348 bytetask.py:205 DEBUG: rank 0 step 1 task allreduce conv1.bias is ready
[1,0]<stderr>:14:16:55.348 bytecore.py:203 DEBUG: rank 0 step 1 task allreduce conv1.bias has been posted into Core with priority 1000
[1,0]<stderr>:14:16:55.356 horovod.py:116 DEBUG: rank 0 calls zero_grad() of step 2
[1,2]<stderr>:14:16:55.356 horovod.py:116 DEBUG: rank 2 calls zero_grad() of step 2
```

**Environment (please complete the following information):**
- Docker Image: bsc-pytorch-horovod (made by pytorch_horovod.Dockerfile with some bugfix)
- OS: Ubuntu18.04 (in the docker image)
- GCC version: gcc version 5.4.0 (in the docker image)
- CUDA and NCCL version: NCCL2.4.7-1 + CUDA10.0 (in the docker image)
- Framework (TF, PyTorch, MXNet): PyTorch1.2.0

**Additional context**
- Test Source Code(pytorch_horovod_mnist.py)
```
from __future__ import print_function

import argparse
import torch
import torch.backends.cudnn as cudnn
import torch.nn.functional as F
import torch.nn as nn
import torch.optim as optim
import torch.utils.data.distributed
from torchvision import datasets, transforms, models
import horovod.torch as hvd
import timeit
import time
import numpy as np
import os

class LeNet(nn.Module):
   def __init__(self):
       super(LeNet, self).__init__()
       self.conv1 = nn.Conv2d(1, 20, 5, 1)
       self.conv2 = nn.Conv2d(20, 50, 5, 1)
       self.fc1 = nn.Linear(4*4*50, 500)
       self.fc2 = nn.Linear(500, 10)
   def forward(self, x):
       x = F.relu(self.conv1(x))
       x = F.max_pool2d(x, 2, 2)
       x = F.relu(self.conv2(x))
       x = F.max_pool2d(x, 2, 2)
       x = x.view(-1, 4*4*50)
       x = F.relu(self.fc1(x))
       x = self.fc2(x)
       return F.log_softmax(x, dim=1)

class MnistResNet(models.resnet.ResNet):
    def __init__(self):
        super(MnistResNet, self).__init__(models.resnet.BasicBlock, [2, 2, 2, 2], num_classes=10)
        self.conv1 = torch.nn.Conv2d(1, 64, 
            kernel_size=(7, 7), 
            stride=(2, 2), 
            padding=(3, 3), bias=False)
        
    def forward(self, x):
        return torch.softmax(
            super(MnistResNet, self).forward(x), dim=-1)

# Benchmark settings
parser = argparse.ArgumentParser(description='PyTorch Synthetic Benchmark',
                                 formatter_class=argparse.ArgumentDefaultsHelpFormatter)
parser.add_argument('--fp16-allreduce', action='store_true', default=False,
                    help='use fp16 compression during allreduce')

parser.add_argument('--model', type=str, default='lenet',
                    help='model to benchmark')
parser.add_argument('--batch-size', type=int, default=32,
                    help='input batch size')

parser.add_argument('--num-warmup-epoches', type=int, default=1,
                    help='number of warm-up batches that don\'t count towards benchmark')
parser.add_argument('--num-batches-per-iter', type=int, default=10,
                    help='number of batches per benchmark iteration')
parser.add_argument('--num-iters', type=int, default=10,
                    help='number of benchmark iterations')
parser.add_argument('--num-classes', type=int, default=1000,
                    help='number of classes')

parser.add_argument('--no-cuda', action='store_true', default=False,
                    help='disables CUDA training')
parser.add_argument('--profiler', action='store_true', default=False,
                    help='enables profiler')
parser.add_argument('--partition', type=int, default=None,
                    help='partition size')
parser.add_argument('--log-interval', type=int, default=20, metavar='N',
                        help='how many batches to wait before logging training status')

args = parser.parse_args()
args.cuda = not args.no_cuda and torch.cuda.is_available()

hvd.init()

if args.cuda:
    # Horovod: pin GPU to local rank.
    torch.cuda.set_device(hvd.local_rank())

cudnn.benchmark = True

# Set up standard model.
#model = getattr(models, args.model)(num_classes=args.num_classes)
if args.model == 'resnet':
    model = MnistResNet()
elif args.model == 'lenet':
    model = LeNet()

if args.cuda:
    # Move model to GPU.
    model.cuda()

optimizer = optim.SGD(model.parameters(), lr=0.01)

# Horovod: (optional) compression algorithm.
compression = hvd.Compression.fp16 if args.fp16_allreduce else hvd.Compression.none

# bytescheduler wrapper
use_bytescheduler = int(os.environ.get('USE_BYTESCHEDULER', '0'))
if use_bytescheduler > 0:
    if args.partition:
        os.environ["BYTESCHEDULER_PARTITION"] = str(1000 * args.partition)
    import bytescheduler.pytorch.horovod as bsc
    bsc.init()

# Horovod: wrap optimizer with DistributedOptimizer.
optimizer = hvd.DistributedOptimizer(optimizer,
                                     named_parameters=model.named_parameters(),
                                     compression=compression)

# Set up dataset
kwargs = {'num_workers': 0, 'pin_memory': True} if args.cuda else {}
mnist = datasets.MNIST(download=True, train=True, root="/home/user/rank"+str(hvd.rank())).train_data.float()

if args.model == 'lenet':
    data_transform = transforms.Compose([transforms.ToTensor(), transforms.Normalize((0.1307,), (0.3081,))])
else:
    data_transform = transforms.Compose([transforms.Resize(224), transforms.ToTensor(), transforms.Normalize((0.1307,), (0.3081,))])

train_loader = torch.utils.data.DataLoader(
       datasets.MNIST(root='/home/ubuntu/jiawei/rank'+str(hvd.rank()), train=True, transform=data_transform), 
       batch_size=args.batch_size, shuffle=True, **kwargs)

test_loader = torch.utils.data.DataLoader(
       datasets.MNIST(root='/home/ubuntu/jiawei/rank'+str(hvd.rank()), train=False, transform=data_transform), 
       batch_size=args.batch_size, shuffle=True, **kwargs)

if use_bytescheduler > 0:
    optimizer = bsc.ScheduledOptimizer(model, optimizer, (args.num_warmup_epoches + args.num_iters) * len(train_loader))

# Horovod: broadcast parameters & optimizer state.
hvd.broadcast_parameters(model.state_dict(), root_rank=0)
hvd.broadcast_optimizer_state(optimizer, root_rank=0)


def log(s, nl=True):
    if hvd.rank() != 0:
        return
    print(s, end='\n' if nl else '')


def train(args, model, train_loader, optimizer):
    model.train()
    for batch_idx, (data, target) in enumerate(train_loader):
        #time = timeit.timeit(benchmark_step, number=args.num_batches_per_iter)
        if args.cuda:
            data, target = data.cuda(), target.cuda()
        optimizer.zero_grad()
        output = model(data)
        loss = F.cross_entropy(output, target)            
        loss.backward()
        optimizer.step()


def test(args, model, test_loader):
    model.eval()
    test_loss = 0
    correct = 0
    with torch.no_grad():
        for data, target in test_loader:
            if args.cuda:
                data, target = data.cuda(), target.cuda()
            output = model(data)
            test_loss += F.nll_loss(output, target, reduction='sum').item() # sum up batch loss
            pred = output.argmax(dim=1, keepdim=True) # get the index of the max log-probability
            correct += pred.eq(target.view_as(pred)).sum().item()

    test_loss /= len(test_loader.dataset)
    print('Test set: Average loss: {:.4f}, Accuracy: {}/{} ({:.0f}%)'.format(
        test_loss, correct, len(test_loader.dataset),
        100. * correct / len(test_loader.dataset)))

log('Model: %s' % args.model)
log('Batch size: %d' % args.batch_size)
device = 'GPU' if args.cuda else 'CPU'
log('Number of %ss: %d' % (device, hvd.size()))

# Warm-up
log('Running warmup...')

#timeit.timeit(benchmark_step, number=args.num_warmup_batches)
train(args, model, train_loader, optimizer)

# Benchmark
log('Running benchmark...')
img_secs = []
enable_profiling = args.profiler & (hvd.rank() == 0)
print("len: " + str(len(train_loader)))

with torch.autograd.profiler.profile(enable_profiling, True) as prof:
    for x in range(args.num_iters):
        st_t = time.clock()
        train(args, model, train_loader, optimizer)
        t = time.clock() - st_t
        img_sec = args.batch_size * len(train_loader) / t
        log('Iter #%d: %.1f img/sec per %s' % (x, img_sec, device))
        img_secs.append(img_sec)
        log('Train throughput')
        test(args, model, train_loader)
        log('Test throughput')
        test(args, model, test_loader)
if enable_profiling:
    prof.export_chrome_trace(os.path.join('pytorch-trace', args.model+'-'+str(hvd.rank()) +'.json'))
    # print(prof)
# Results
img_sec_mean = np.mean(img_secs)
img_sec_conf = 1.96 * np.std(img_secs)
log('Img/sec per %s: %.1f +-%.1f' % (device, img_sec_mean, img_sec_conf))
log('Total img/sec on %d %s(s): %.1f +-%.1f' %
    (hvd.size(), device, hvd.size() * img_sec_mean, hvd.size() * img_sec_conf))

```

**Comment by ymjiang** [comment]
Hi @pengyanghua , could you please take a look?

**Comment by pengyanghua** [comment]
@bjwdttz Thanks for your report. We will reproduce this bug according to your description and fix it soon. You may try moving L201 just before L198 in bytecore.py to see if this error still exists.

**Comment by bjwdttz** [comment]
> @bjwdttz Thanks for your report. We will reproduce this bug according to your description and fix it soon. You may try moving L201 just before L198 in bytecore.py to see if this error still exists.

Thanks for your help. It works now! But the tracing file only contains ALLREDUCEQUEUE and ALLREDUCECOMMUNICATION two functions, while the example you provided [here](https://github.com/bytedance/byteps/blob/bytescheduler/bytescheduler/docs/timeline.png) has different push and pull functions.

Here's the screenshot for the tracing file I generated:
![tl1](https://user-images.githubusercontent.com/22519692/65832062-999c3a80-e2c8-11e9-9dfb-7531aa0993f4.png)

I am wondering if my tracing file is an incomplete one or the pytorch-horovod-bytescheduler just generates different tracing file from other methods. Could you please help me with that?

**Comment by pengyanghua** [comment]
@bjwdttz  Your trace is ok. The example shows the timeline of PS architecture. For Horovod, it does not have push or pull operations. So far ByteScheduler supports profiling the queuing time and communication time in ByteCore. For communication details, you may resort to the profiler of each communication library, e.g., Horovod.

**Comment by bjwdttz** [comment]
> @bjwdttz Your trace is ok. The example shows the timeline of PS architecture. For Horovod, it does not have push or pull operations. So far ByteScheduler supports profiling the queuing time and communication time in ByteCore. For communication details, you may resort to the profiler of each communication library, e.g., Horovod.

Thank you!
