### ISSUE TITLE
cuda driver version is insufficient for cuda runtime version

### ISSUE THREAD

**Issue by blackjack2016** [bytedance/byteps#185]
I downloaded docker image, and then ran tensorflow according to step by step tutorial, but found an error.
![image](https://user-images.githubusercontent.com/44971530/71509621-e511b500-28c6-11ea-9fbe-55cc4593a686.png)

**Comment by zhongyuchen** [comment]
Could you give the results of `nvidia-smi` in your host machine and in the container? And have you run the container with `nvidia-docker`?

**Comment by ymjiang** [comment]
Your nvidia-docker version might be too old to run cuda 10. Would you update the driver to at least `410.48`?

**Comment by blackjack2016** [comment]
Thank you for your advice. I have solved the problem. I have another question and i wonder if you can help me.
How can I train an original tensorflow job on the base of your docker container?
Because I want to see the difference performance between Byteps and tensorflow, I think i should change&nbsp;synthetic_benchmark.py and delete 'import byteps.tensorflow as bps',but this document still exist many bps,should i change them into tf?
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Yimin Jiang"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月27日(星期五) 晚上6:38
收件人:&nbsp;"bytedance/byteps"<byteps@noreply.github.com&gt;;
抄送:&nbsp;"914219011"<tyh7020530@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [bytedance/byteps] cuda driver version is insufficient for cuda runtime version (#185)




Your nvidia-docker version might be too old to run cuda 10. Would you update the driver to at least 410.48?

**Comment by ymjiang** [comment]
If you want to run original TF, then you should probably refer to this repo: https://github.com/tensorflow/benchmarks. Our docker image does not support that yet.

But there is a fast way for you to compare TF-BytePS with TF-Horovod. You can change `import byteps.tensorflow as bps` to `import horovod.tensorflow as bps`.

**Comment by blackjack2016** [comment]
Thank you,this way I've tried before,but horovod doesn't exist in docker ,should i install horovod on my computer?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Yimin Jiang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月16日(星期天) 下午4:37
收件人:&nbsp;"bytedance/byteps"<byteps@noreply.github.com&gt;;
抄送:&nbsp;"914219011"<tyh7020530@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [bytedance/byteps] cuda driver version is insufficient for cuda runtime version (#185)




If you want to run original TF, then you should probably refer to this repo: https://github.com/tensorflow/benchmarks. Our docker image does not support that yet.
 
But there is a fast way for you to compare TF-BytePS with TF-Horovod. You can change import byteps.tensorflow as bps to import horovod.tensorflow as bps.

**Comment by ymjiang** [comment]
Maybe you should do `pip3 install horovod` in the docker image.

**Comment by blackjack2016** [comment]
Thank you for your advice. I ran the program according to your method and got the following results.









The first picture is run by byteps,others are run by horovod.


I don't know why when I'm running horovod, only one GPU is running, and the other is not used?
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Yimin Jiang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月16日(星期天) 下午5:20
收件人:&nbsp;"bytedance/byteps"<byteps@noreply.github.com&gt;;
抄送:&nbsp;"914219011"<tyh7020530@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [bytedance/byteps] cuda driver version is insufficient for cuda runtime version (#185)




Maybe you should do pip3 install horovod in the docker image.

**Comment by ymjiang** [comment]
@blackjack2016 , it seems that your picture is missing.

**Comment by blackjack2016** [comment]
I'm sorry for this problem,maybe there is something wrong with my email? Can you see the picture this time? The first picture is running byteps,and others are running horovod,I don't know why only one GPU is working when running horovod while both GPU &nbsp;are working normally by byteps. This time I just download horovod in docker and change 'import byteps.tensorflow as bps' into 'import horovod.tensorflow as bps' in synthetic_benchmark.py
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Yimin Jiang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月18日(星期二) 下午3:49
收件人:&nbsp;"bytedance/byteps"<byteps@noreply.github.com&gt;;
抄送:&nbsp;"914219011"<tyh7020530@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [bytedance/byteps] cuda driver version is insufficient for cuda runtime version (#185)




@blackjack2016 , it seems that your picture is missing.

**Comment by ymjiang** [comment]
@blackjack2016 , I still cannot see the picture. Did you use mpirun to launch Horovod?

**Comment by blackjack2016** [comment]
By the way, if I want to understand the project more comprehensively, what other aspects of knowledge do I need to learn? Can you give me some advice?


------------------ 原始邮件 ------------------
发件人: "Yimin Jiang"<notifications@github.com&gt;; 
发送时间: 2020年2月18日(星期二) 晚上6:12
收件人: "bytedance/byteps"<byteps@noreply.github.com&gt;; 
抄送: "914219011"<tyh7020530@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [bytedance/byteps] cuda driver version is insufficient for cuda runtime version (#185)




@blackjack2016 , I still cannot see the picture. Did you use mpirun to launch Horovod?
