### ISSUE TITLE
NCCL error: invalid usage

### ISSUE THREAD

**Issue by richlaji** [bytedance/byteps#38]
**Describe the bug**
When running the example/pytorch/train_mnist_byteps.py, at `bps.broadcast_parameters(model.state_dict(), root_rank=0)`
an error was raised
`byteps/common/core_loops.cc :309] Check failed: r == ncclSuccess NCCL error: invalid usage`

**To Reproduce**
```
export NVIDIA_VISIBLE_DEVICES=4,5,6,7  # say you have 4 GPUs
export CUDA_VISIBLE_DEVICES=4,5,6,7  # say you have 4 GPUs
export DMLC_WORKER_ID=0 # your worker id
export DMLC_NUM_WORKER=1 # you only have one worker
export DMLC_ROLE=worker # your role is worker

export DMLC_NUM_SERVER=1
export DMLC_PS_ROOT_URI=127.0.0.1
export DMLC_PS_ROOT_PORT=1234

python byteps/launcher/launch.py python example/pytorch/train_mnist_byteps.py
```

**Expected behavior**
Expected to no error.

**Environment (please complete the following information):**
 - OS: Ubuntu 16.04
 - GCC version: 5.4.0
 - CUDA and NCCL version: CUDA 9.0, NCCL 2.4.8
 - Framework (TF, PyTorch, MXNet): Pytorch

**Comment by ymjiang** [comment]
We have seen similar cases before due to the gcc issue. Can you try to pin down gcc to 4.9 and then build again? Generally, the steps are:

1. Uninstall your byteps (optional, depend on you)
```
pip uninstall -y byteps
python setup.py clean --all
```

2. Pin down gcc to 4.9, here is an example: https://github.com/bytedance/byteps/blob/master/docker/Dockerfile.worker.pytorch.cu90#L123-L131

3. Install byteps again

**Comment by bobzhuyb** [comment]
Which GPU are you using?

**Comment by richlaji** [comment]
Problem solved! Thank you!

**Comment by bobzhuyb** [comment]
@richlaji Great! Did you solve the problem by using gcc 4.9?

**Comment by bobzhuyb** [comment]
I believe this is the same problem..
https://github.com/bytedance/byteps/issues/35
